/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */
import * as Hapi from '@hapi/hapi'
import fetch from 'node-fetch'
import { logger } from '@countryconfig/logger'
import {
  MOSIP_INTEGRATION_CLIENT_ID,
  MOSIP_INTEGRATION_CLIENT_SECRET,
  USER_MANAGEMENT_URL
} from '@countryconfig/constants'

interface RecordScope {
  type: string
  options: { event: string[] }
}

interface IntegrationConfig {
  name: string
  scopes: RecordScope[]
  /**
   * Optional pre-shared credentials. When set, user-mgnt seeds the integration
   * with exactly these values so the integrating system (e.g. mosip-api) can
   * authenticate immediately using the same client id/secret it carries in its
   * own env — no manual "Refresh secret" step required. When omitted, user-mgnt
   * generates credentials and an NSA reveals them via the Integrations page.
   */
  clientId?: string
  clientSecret?: string
}

/**
 * Integrations to register on startup. Each entry maps to a POST /createIntegration call.
 *
 * Credentials are optional. If a `clientId`/`clientSecret` pair is provided (e.g.
 * via the MOSIP_INTEGRATION_CLIENT_ID / MOSIP_INTEGRATION_CLIENT_SECRET env vars),
 * user-mgnt seeds the integration with exactly those values. This is how the MOSIP
 * integration shares one set of credentials between OpenCRVS and mosip-api's
 * OPENCRVS_CLIENT_ID / OPENCRVS_CLIENT_SECRET. If no credentials are provided, they
 * are generated by user-mgnt and a National System Admin retrieves them via the
 * Integrations UI (Configurations → Integrations → Reveal keys → Refresh secret).
 *
 * Example (MOSIP):
 * {
 *   name: 'MOSIP',
 *   scopes: [
 *     { type: 'record.register', options: { event: ['birth', 'death'] } }
 *   ]
 * }
 */
const INTEGRATIONS: IntegrationConfig[] = [
  {
    name: 'MOSIP',
    scopes: [
      { type: 'record.register', options: { event: ['birth', 'death'] } }
    ],
    clientId: MOSIP_INTEGRATION_CLIENT_ID || undefined,
    clientSecret: MOSIP_INTEGRATION_CLIENT_SECRET || undefined
  }
]

export async function systemReadyHandler(
  request: Hapi.Request,
  h: Hapi.ResponseToolkit
) {
  const bearerToken = request.headers.authorization

  for (const integration of INTEGRATIONS) {
    try {
      const res = await fetch(
        new URL('/createIntegration', USER_MANAGEMENT_URL).toString(),
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: bearerToken
          },
          body: JSON.stringify({
            name: integration.name,
            scopes: integration.scopes,
            // Only forward credentials when configured — otherwise let
            // user-mgnt generate them.
            ...(integration.clientId && { clientId: integration.clientId }),
            ...(integration.clientSecret && {
              clientSecret: integration.clientSecret
            })
          })
        }
      )

      if (!res.ok) {
        logger.warn(
          `createIntegration for "${integration.name}" failed: ${res.status} ${await res.text()}`
        )
      } else {
        logger.info(`Integration "${integration.name}" registered successfully`)
      }
    } catch (error) {
      logger.warn(
        `createIntegration for "${integration.name}" threw: ${error instanceof Error ? error.message : error}`
      )
    }
  }

  return h.response().code(200)
}
