# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Deploy & run E2E
run-name: "Triggered by ${{ github.actor }} (core: ${{ inputs.core-image-tag }}, countryconfig: ${{ inputs.countryconfig-image-tag }}) to e2e"
on:
  repository_dispatch:
    types: [run_e2e]
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      core-image-tag:
        description: Core image tag
        required: true
        default: 'v2.0.0'
      countryconfig-image-tag:
        description: Your Country Config image tag
        required: true
        default: 'v2.0.0'

concurrency:
  group: ci-build
  cancel-in-progress: false

jobs:
  # wait-30s:
  #   # Avoid a race condition when PRs exist in both testland and core.
  #   # The delay gives the other PR time to merge before reading develop.
  #   name: Wait 30 seconds
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Wait 30 seconds
  #       run: sleep 30

  get-core-commit:
    # needs: wait-30s
    name: Resolve latest core tag
    runs-on: ubuntu-latest
    outputs:
      latest_commit_sha: ${{ steps.get_latest_commit.outputs.commit_sha }}
    steps:
      - name: Checkout opencrvs-core repository
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
        uses: actions/checkout@v6
        with:
          repository: 'opencrvs/opencrvs-core'
          ref: 'develop'
      - name: Get latest commit SHA
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
        id: get_latest_commit
        run: echo "commit_sha=$(git rev-parse HEAD | cut -c 1-7)" >> $GITHUB_OUTPUT

  get-country-config-commit:
    name: Resolve latest Testland tag
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
      - name: Get short commit hash
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
  
  trigger-e2e:
    name: Trigger E2E workflow
    runs-on: ubuntu-latest
    needs: 
      - get-core-commit
      - get-country-config-commit
    outputs:
      run_id: ${{ steps.trigger_e2e.outputs.run_id }}
      run_url: ${{ steps.trigger_e2e.outputs.run_url }}
    steps:
      - name: Print resolved e2e properties
        env:
          CORE_IMAGE_TAG: ${{ inputs.core-image-tag || needs.get-core-commit.outputs.latest_commit_sha }}
          COUNTRYCONFIG_IMAGE_TAG: ${{ inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha }}
        run: |
          echo "Core image tag: $CORE_IMAGE_TAG"
          echo "Country config image tag: $COUNTRYCONFIG_IMAGE_TAG"
      - name: Trigger E2E
        env:
          CORE_IMAGE_TAG: ${{ inputs.core-image-tag || needs.get-core-commit.outputs.latest_commit_sha }}
          COUNTRYCONFIG_IMAGE_TAG: ${{ inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha }}
        id: trigger_e2e
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TESTLAND_WORKFLOW_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'opencrvs',
              repo: 'opencrvs-testland-infrastructure',
              workflow_id: 'deploy-and-e2e.yml',
              ref: 'develop',
              return_run_details: true,
              headers: {
                'X-GitHub-Api-Version': '2026-03-10',
              },

              inputs: {
                'core-image-tag': '${{ env.CORE_IMAGE_TAG }}',
                'countryconfig-image-tag': '${{ env.COUNTRYCONFIG_IMAGE_TAG }}'
              },
            });

            console.log(JSON.stringify(result.data, null, 2));

            const runId = result.data.workflow_run_id;

            if (!runId) {
              throw new Error(`workflow_run_id was not returned. Response: ${JSON.stringify(result.data)}`);
            }

            core.setOutput('run_id', runId);
            core.setOutput('run_url', result.data.html_url);

            console.log(`Triggered runId: ${runId}`);
            console.log(`Run URL: ${result.data.html_url}`);

      - name: Print link to E2E workflow run
        id: print-links
        run: |
          E2E_RUN_LINK="${{ steps.trigger_e2e.outputs.run_url }}"
          DEPLOYMENT_LINK="https://e2e.opencrvs.dev"

          echo """
          # E2E Environment summary
          Action workflow (pipeline): $E2E_RUN_LINK

          Web link: $DEPLOYMENT_LINK
          """ >> $GITHUB_STEP_SUMMARY

          echo "deployment_link=$DEPLOYMENT_LINK" >> $GITHUB_OUTPUT
  listen-e2e:
    needs: [trigger-e2e]
    runs-on: ubuntu-24.04
    steps:
      - name: Wait for Environment Deployment (Deploy Job)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TESTLAND_WORKFLOW_TOKEN }}
          script: |
            const owner = 'opencrvs';
            const repo = 'opencrvs-testland-infrastructure';
            const runId = ${{ needs.trigger-e2e.outputs.run_id }};
            let deployJobCompleted = false;

            // Check if deploy job has completed
            while (!deployJobCompleted) {
              const workflowRun = await github.rest.actions.getWorkflowRun({
                owner,
                repo,
                run_id: runId
              });
              const jobs = await github.rest.actions.listJobsForWorkflowRun({
                owner,
                repo,
                run_id: runId
              });

              const deployJob = jobs.data.jobs.find(job => job.name === 'deploy / seed-data / seed-data');
              const cancelled = jobs.data.jobs.find(job => job.conclusion === 'cancelled');

              if (cancelled) {
                throw new Error('E2E workflow was cancelled');
              }

              if (deployJob && deployJob.status === 'completed') {
                deployJobCompleted = true;

                if (deployJob.conclusion !== 'success') {
                  throw new Error('Deploy job failed');
                }

                console.log('Deploy job completed successfully');
              }

              if(workflowRun.data.status === 'completed') {
                deployJobCompleted = true;

                if (workflowRun.data.conclusion !== 'success') {
                  throw new Error('E2E workflow failed');
                }
              }

              if (!deployJobCompleted) {
                await new Promise(resolve => setTimeout(resolve, 10000));
              }
            }
  notify-slack:
    name: Notify Slack on Failure
    runs-on: ubuntu-latest
    needs: [listen-e2e]
    if: always() && failure()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C08FCLKER8X'
          slack-message: "❌ E2E pipeline triggered by ${{ github.event.client_payload.actor || github.actor }}'s commit failed. Check the logs at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify-slack-success:
    name: Notify Slack on success
    runs-on: ubuntu-latest
    needs: [listen-e2e]
    if: success()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C08FCLKER8X'
          slack-message: '✅ E2E pipeline finished successfully, triggered by ${{ github.event.client_payload.actor || github.actor }}. Check the logs at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
